version: 1.0
name: dapp_build
stages:
  template-init:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/my-erc20

  build:
    needs:
      - template-init
    steps:
      - name: npm build
        run: |
          cd app
          npm install
          npm run build
          docker build -t mohaijiang/my-erc20 .
