version: 1.0
name: dapp_build
stages:
  template-init:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/my-erc20

  deploy:
    needs:
      - template-init
    steps:
      - name: deploy to docker
        run: |
          cd app
          docker rm -f my-erc20
          docker run -d -p 80:80 --name my-erc20 mohaijiang/my-erc20
      - name: deploy to ipfs
        run: |
          cd app
          ipfs add -r ./dist
