version: 1.0
name: slither-check
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://github.com/abing258/solidity_contracts.git
          branch: main
  code-compile:
    needs:
      - git-clone
    steps:
      - name: slither-check
        uses: slither-check
        with:
          path:
