# The rpc address of the chain node
RpcAddr     = "wss://testnet-rpc1.cess.cloud/ws/"
# The IP address of the machine's public network used by the scheduler program
ServiceAddr = "0.0.0.0"
# Port number monitored by the scheduler program
ServicePort = "8080"
# Data storage directory
DataDir     = "temp"
# Phrase or seed of wallet account
AccountSeed = "seed laundry smoke stereo legend ecology obtain scheme auction ride family what"